### ISSUE TITLE
New Collection W11 for Events classification section (BODCNVS-493)

### ISSUE THREAD

**Issue by alko-k** [nvs-vocabs/SWEMarineProfileVocabs#1]
Dear colleagues,

**collection W11: SensorML Event   Classification Terms**

 has been proposed for the classification section of Events.
The sensorML for Events (including different sections) is described in the file attached:
The proposed terms are:

**Event Process**: A   general ongoing activity a device can do and consists of a sequence of   punctuated actions (including malfunctions and deliberate actions).

**Event Subjec**t: The   scientific purpose of the event.

**Event Action**:  A step,   phase or moment in an ongoing process, and can be deliberate or incidentally.   For instance 'Start', 'End' or 'Failure'

Your feedback is needed please.
[Events.txt](https://github.com/nvs-vocabs/SWEMarineProfileVocabs/files/4756449/Events.txt)

**Comment by huberrob** [comment]
Hi Alexandra,

is there the need to classify Events anyway? What is the origin or motivation of this proposal?
Maybe you can give some other examples, the http://ontologies.ef-ears.eu/ears2/1/#pro_1 is not really self explaining ;)

Robert

**Comment by tvandenberghe** [comment]
Hi Robert,
The origin of the proposal is in the Eurofleets+ project which identifies 3 levels ("classifications") in events: device category, device, process P, action A, subject S and property. This proposal adds P, A ans S as event classifiers. This allows a more fine-grained description beyond what is now available in http://vocab.nerc.ac.uk/collection/W03/current/ which you can think of as process+action combined. The correct combinations (no green dogs) stem from a base template ontology, the one you linked to. The specific need to express the eurofleets events in sensorml is requested at this moment as we intend to store these events in the history section of a device or sampler (and have the software ready to autogenerate the sml).

**Comment by nvsvocabs** [comment]
> Hi Alexandra,
> 
> is there the need to classify Events anyway? What is the origin or motivation of this proposal?
> Maybe you can give some other examples, the http://ontologies.ef-ears.eu/ears2/1/#pro_1 is not really self explaining ;)
> 
> Robert

Hi @huberrob , thanks for your response.
Does @tvandenberghe answer cover you?

**Comment by huberrob** [comment]
For me these types seem to be a bit generic but if you need it .. go ahead. ;)

**Comment by gwemon** [comment]
Closing. Collection created and initial population completed (see https://vocab.nerc.ac.uk/collection/W11/)
