### ISSUE TITLE
New Term for W08: Service Provider

### ISSUE THREAD

**Issue by adamml** [nvs-vocabs/SWEMarineProfileVocabs#3]
Following up on #2, I'd also like to request:

**Service Provider** Relevant contact information for an individual or organisation which provides skilled or specialised services relevant to a device or system to another individual or organisation.

**Comment by adamml** [comment]
Bump

**Comment by gwemon** [comment]
Our ref: BODCNVS-668

**Comment by louatbodc** [comment]
New term created:

CONT0007	Service Provider
